// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwaJKSqJVnmC7Z2s6fZNSWr8lu4w5xlH8',
    appId: '1:681857383834:web:28dab18cb6c158bf548e23',
    messagingSenderId: '681857383834',
    projectId: 'prectise-first-project',
    authDomain: 'prectise-first-project.firebaseapp.com',
    storageBucket: 'prectise-first-project.appspot.com',
    measurementId: 'G-7HHJLY3EE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCax0PHES1UpOUNUQYhG_xWbBTMTt6T7gQ',
    appId: '1:681857383834:android:ce615931cb3f7276548e23',
    messagingSenderId: '681857383834',
    projectId: 'prectise-first-project',
    storageBucket: 'prectise-first-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtov7kuJyAhFVodKFpS8Pcjf5s1LD0HnQ',
    appId: '1:681857383834:ios:64b3e18c0cb00a95548e23',
    messagingSenderId: '681857383834',
    projectId: 'prectise-first-project',
    storageBucket: 'prectise-first-project.appspot.com',
    iosClientId: '681857383834-6m00oo6ptjk7c1o5hebnq6k6as1do46g.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiseFunctionalityScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtov7kuJyAhFVodKFpS8Pcjf5s1LD0HnQ',
    appId: '1:681857383834:ios:64b3e18c0cb00a95548e23',
    messagingSenderId: '681857383834',
    projectId: 'prectise-first-project',
    storageBucket: 'prectise-first-project.appspot.com',
    iosClientId: '681857383834-6m00oo6ptjk7c1o5hebnq6k6as1do46g.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiseFunctionalityScreen',
  );
}
